require: rubocop-performance

AllCops:
  # note Exclude: overrides, does not merge with, default.
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - '.git/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'config/environments/*.rb'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'db/migrate/**/*'
    - 'config/initializers/*'

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/IndentationConsistency:
  EnforcedStyle: 'indented_internal_methods'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'db/migrate/*'
